[background]
path = "/home/vlad/Pictures/Wallpapa/scenery-purple.png"
fit = "Cover"

[GTK]
application_prefer_dark_theme = true
theme_name = "Adwaita"
icon_theme_name = "Adwaita"
font_name = "Sans 11"
application_cssfile = "/etc/greetd/regreet.css"
