cursor {{ cursor }}
background #000000
foreground {{ foreground }}

color0 {{ color0 }}
color1 {{ color1 | saturate(50) }}
color2 {{ color2 | saturate(50) }}
color3 {{ color3 | saturate(50) }}
color4 {{ color4 | saturate(50) }}
color5 {{ color5 | saturate(50) }}
color6 {{ color6 | saturate(50) }}
color7 {{ color7 }}

color8 {{ color8 }}
color9 {{ color9 | saturate(50) }}
color10 {{ color10 | saturate(50) }}
color11 {{ color11 | saturate(50) }}
color12 {{ color12 | saturate(50) }}
color13 {{ color13 | saturate(50) }}
color14 {{ color14 | saturate(50) }}
color15 {{ color15 }}

mark1_foreground {{ color6 | saturate(0.2) }}
mark2_foreground {{ color7 | saturate(0.2) }}
mark3_foreground {{ color6 | saturate(0.2) }}
